const LOGIN_STATE: any = {
  DEFAULT: "IDENTIFIER",
  PASSWORD_SECTION: "PASSWORD_SECTION",
  MPIN_SECTION: "MPIN_SECTION",
  PASSWORD_SUCCESS: "PASSWORD_SUCCESS",
  // PASSWORD_FORGOT_SUCCESS: "PASSWORD_FORGOT_SUCCESS",
  PASSWORD_RENEW_SUCCESS: "PASSWORD_RENEW_SUCCESS",
  PASSWORD_RESET_SUCCESS: "PASSWORD_RESET_SUCCESS",
  UNBLOCK_SUCCESS: "UNBLOCK_SUCCESS",
  // CREATE_MPIN_SUCCESS: "CREATE_MPIN_SUCCESS",
  // VALIDATE_MPIN_SUCCESS: "VALIDATE_MPIN_SUCCESS",
  /* Challenge success messages */
  RENEW_AND_HOME: "RENEW_AND_HOME",
  RENEW_AND_MPIN: "RENEW_AND_MPIN",
  MPIN_AND_HOME: "MPIN_AND_HOME",
  HOME: "HOME",
  /* Common error message */
  SUBMISSION_ERROR: "SUBMISSION_ERROR",
}

export { LOGIN_STATE };
